language: android

sudo: false

jdk: oraclejdk8

# Update to the lastest JDK8
addons:
  apt:
    packages:
      - oracle-java8-installer

before_cache:
  - rm -f ${TRAVIS_BUILD_DIR}/gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/gradle/caches/
    - ${TRAVIS_BUILD_DIR}/gradle/wrapper/dists/

notifications:
  email:
    -  moses@futurice-nonda.flowdock.com 

env:
  global:
#    - INSTALL_PKGS='build-tools-23.0.3,android-23'
#    - UPDATE_PKGS='platform-tools,tools,extra-android-m2repository,extra-google-m2repository'
    - GRADLE_USER_HOME="${TRAVIS_BUILD_DIR}/gradle"
    - ADB_INSTALL_TIMEOUT=14 # minutes (2 minutes by default)
#    - AVD_DEBUG='init,avd_config,nand_limits,keys,adb,adbserver,adbclient'
#    - ANDROID_LOG_TAGS='NetworkStats:S dalvikvm:S Zygote:S Resources:S *:D'
  matrix:
    - AVD_TARGET=android-15
    - AVD_TARGET=android-17
    - AVD_TARGET=android-19
    - AVD_TARGET=android-21
    - AVD_TARGET=android-23 TARGET_PKGS=sys-img-armeabi-v7a-android-23

before_install:
  - cd ./ReactiveCascade

install:
  - ./execute install-and-update-sdk # install and update the SDK based on env vars or Acib defaults
  - ./execute create-and-start-device # create and start a device based on env vars or Acib defaults
  - ./execute wait-for-device-online # start adbd, wait for device connected and show android serial
  - ./gradlew --version # show version and download Gradle Wrapper when is not present in cache
  - ./gradlew clean # clean project and download Android dependencies when are not present in cache
  - ./gradlew assemble --stacktrace
  - ./gradlew test

before_script:
  - ./execute wait-for-device-ready

script:
  - ./gradlew connectedCheck

after_script:
  - ./execute show-android-test-results
